### ISSUE TITLE
Refactor ineq cards

### ISSUE THREAD

**Issue by srfoster** [thoughtstem/morugamu#11]
The inequality cards rule system has a pretty cool theme.  But unlike, say, the boolean algebra system -- that theme is embedded in the rule system's render function.  This should be factored out.  See any of the other rule systems for guidelines.

**Comment by JuliaB1** [comment]
Created a new file in the themes folder (emoji-inequality.rkt) to match the corresponding themes of the boolean algebra and clock arithmetic puzzle systems.
