### ISSUE TITLE
Fix the number-all function

### ISSUE THREAD

**Issue by srfoster** [thoughtstem/morugamu#12]
This function is used to number puzzle cards.  I want to be able to use it to number any list of images (rule cards, tiles, printable sheets, etc.)  Currently the default placement of the number makes this impossible.  Make the function more generally useful (see the print-all.rkt file, where I'm using the function unsuccessfully to try to put numbers on the rule cards).

**Comment by JuliaB1** [comment]
We changed the place-num function so that a "place-image" call is now an "overlay/offset" call

**Comment by JuliaB1** [comment]
We also changed the offset x and y values to be more responsive: they accommodate for any image's width and height

**Comment by gbm2cool** [comment]
We created a file called "testing-numbers.rkt" which shows that the "overlay/offset" call will place a number in the top right corner of an image of any size.
